[[headers]]
  for = "*.js"
  [headers.values]
    cache-control = "public, max-age=604800, must-revalidate" # one week

[[headers]]
  for = "*.css"
  [headers.values]
    cache-control = "public, max-age=604800, must-revalidate" # one week

[[headers]]
  for = "*.jpg"
  [headers.values]
    cache-control = "public, max-age=604800, must-revalidate" # one week

[[headers]]
  for = "*.png"
  [headers.values]
    cache-control = "public, max-age=604800, must-revalidate" # one week

[[headers]]
  for = "*.webp"
  [headers.values]
    cache-control = "public, max-age=604800, must-revalidate" # one week

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    # Multi-value headers are expressed with multi-line strings.
    # One Week cache control
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "no-referrer"
  X-Content-Type-Options = "nosniff"
