[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    # Multi-value headers are expressed with multi-line strings.
    # One Week cache control
  cache-control = "public, max-age=86400, must-revalidate" # one day
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "no-referrer"
  X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.js"
  [headers.values]
    cache-control = "public, max-age=604800, must-revalidate" # one week

[[headers]]
  for = "*.css"
  [headers.values]
    cache-control = "public, max-age=604800, must-revalidate" # one week

[[headers]]
  for = "*.jpg"
  [headers.values]
    cache-control = "public, max-age=604800, must-revalidate" # one week

[[headers]]
  for = "*.png"
  [headers.values]
    cache-control = "public, max-age=604800, must-revalidate" # one week

[[headers]]
  for = "*.webp"
  [headers.values]
    cache-control = "public, max-age=604800, must-revalidate" # one week

[[headers]]
  for = "*.ttf"
  [headers.values]
    cache-control = "public, max-age=31536000, must-revalidate" # max value

[[redirects]]
  from = "http://www.menepet.me/*"
  to = "http://www.mene.pet/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.menepet.me/*"
  to = "https://www.mene.pet/:splat"
  status = 301
  force = true

[build.environment]
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"

# Cypress plugin
[[plugins]]
  package = "netlify-plugin-cypress"
  # [plugins.inputs]
  #   # run E2E tests against the deployed URL
  #   record = false
  #   group = 'deployed'
  # [plugins.inputs.postBuild]
  #   # run E2E tests against locally built site
  #   # before deploying it
  #   enable = true
  #   record = false
  #   group = 'built'
